### ISSUE TITLE
Any documentation on using django-image-cropping with google storage backend?

### ISSUE THREAD

**Issue by jkesler** [jonasundderwolf/django-image-cropping#100]
Heya!

This is a fantastic plugin and I have really enjoyed playing with it, it works really well locally for us. 

We are working on a site that is using google app engine and google storage and I can't seem to find any kind of documentation or examples when using alternate storage backends.

Is there any way you might be able to point me to where in the source I would need to add some additional logic to support google storage? Thank you a bunch for your time and great work on this library.

**Comment by anrie** [comment]
Hey @jkesler,

most the actual work of django-image-cropping is in fact done by [easy-thumbnails](https://github.com/SmileyChris/easy-thumbnails).

At least for [S3](https://github.com/jonasundderwolf/django-image-cropping/issues/76#issuecomment-148963970) changing the easy-thumbnail's [storage backend](http://easy-thumbnails.readthedocs.io/en/2.1/ref/settings/#easy_thumbnails.conf.Settings.THUMBNAIL_DEFAULT_STORAGE) seemed to do the trick.

**Comment by jkesler** [comment]
@anrie Thank you so much for your quick reply. I was not too familiar with easy-thumbnails but after reading your comment I was quickly able to find the answer. 

I simple had to add the following to my application settings and everything is working beautifully

THUMBNAIL_DEFAULT_STORAGE = 'storages.backends.gs.GSBotoStorage'

Thanks again <3

**Comment by anrie** [comment]
Ah, great!
I see that I add a section about remote storages to the docs.
