### ISSUE TITLE
Avoid hardcoded options

### ISSUE THREAD

**Issue by arogachev** [jonasundderwolf/django-image-cropping#106]
Some options, such as `minSize` are now hardcoded (`minSize` is set to `[5, 5]` for example). It's better to avoid that and add possibility to set it via settings.

**Comment by anrie** [comment]
@arogachev I agree. That would make sense as setting. Feel free to send a PR!

**Comment by anrie** [comment]
Okay, I think the issue is covered sufficiently by #105 so I am closing this.
