### ISSUE TITLE
django-image-cropping does not show cropping tool in the admin

### ISSUE THREAD

**Issue by fargalaxy1** [jonasundderwolf/django-image-cropping#113]
Hi and thank you for your work!
I've found an issue while using the image cropping tool. I described it in this [StackOverflow](http://stackoverflow.com/questions/42255716/django-image-cropping-does-not-show-cropping-tool-in-the-admin) question.
Could you suggest a way to solve it?

**Comment by derek-adair** [comment]
As the users in that question have pointed out, you are probably not hosting media files properly.

**Comment by anrie** [comment]
Yes, I agree, this seems to be problem with serving the static assets and media files.
So I am afraid there's not much we can do on our end.
