### ISSUE TITLE
cropping tool not showing in admin with django 1.11

### ISSUE THREAD

**Issue by Aupourbau** [jonasundderwolf/django-image-cropping#115]
![screen shot 2017-04-27 at 09 35 03](https://cloud.githubusercontent.com/assets/17118172/25472718/d57bfdfc-2b2c-11e7-8041-c01a133efcfb.png)

**Comment by felixkohtz** [comment]
I  can not confirm this -- using django 1.11.1
Looks like you have an error in the code which you should maybe provide to get help.

![admin_crop](https://cloud.githubusercontent.com/assets/13085282/26521044/4e8f5710-42df-11e7-981c-142562a95ed1.png)

**Comment by Aupourbau** [comment]
It works when free_crop=True, but not when we put a fixed size in my case:
    image = ImageCropField(
        _('image'),
        upload_to='project/%Y/%m/%d'
    )
    cropping_image = ImageRatioField(
        'image',
        '1600x900',
    )

**Comment by Aupourbau** [comment]
The issue seems to be fixed with Django 1.11.2
