### ISSUE TITLE
ModelForm - ImageRatioField does not show Image (Django 1.11.1)

### ISSUE THREAD

**Issue by felixkohtz** [jonasundderwolf/django-image-cropping#116]
Django==1.11.1
django-image-cropping==1.0.4
python 3.5.3

If i follow instructions how to add a cropping widget outside the admin, the ImageRatioField does not show any image.

Screenshot:

![crop](https://cloud.githubusercontent.com/assets/13085282/26520975/c383373c-42dd-11e7-9d80-28a9b8a1fd2c.png)
models.py
```
from django.db import models
from image_cropping import ImageCropField, ImageRatioField

class event(models.Model):
	date = models.DateField()
	name = models.CharField(max_length=512)
	flyer = ImageCropField(blank=True, upload_to='media')
	cropping = ImageRatioField('flyer', '60x60')

	def __str__(self):
		return self.name
```
forms.py
```
from django import forms
from .models import event

class addEventForm(forms.ModelForm):

	class Meta:
		model = event
		fields = ('date', 'name', 'flyer', 'cropping')
```

form.html
```
{% load cropping %}

<head>
{{ form.media }}
</head>

<body> 
<form method='POST' action="">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="submit">
</form>
</body>
```

**Comment by coler-j** [comment]
You figure this out? Mine only shows the image after saving the image to the model and reloading the form with the saved instance.

**Comment by anrie** [comment]
Does the example app that comes with django-image-cropping work for you?

**Comment by felixkohtz** [comment]
The example is working - just tried it.

$ pip freeze
```
Django==1.11.5
django-appconf==1.0.1
django-image-cropping==1.1.0
easy-thumbnails==2.4.2
olefile==0.44
Pillow==4.2.1
pkg-resources==0.0.0
pytz==2017.2
six==1.11.0
```
**Screenshot:**


![screen](https://user-images.githubusercontent.com/13085282/30933229-461b8148-a3ca-11e7-9a16-ca7cae3a43f9.png)




I will try later to implement it in my project.

Thank you for looking into/fixing it!

**Comment by felixkohtz** [comment]
But yes, i also have to save the image first, after that the cropping is displayed.

Is this how it should work?

**Comment by felixkohtz** [comment]
Implemented it and works great. Thanks!
