### ISSUE TITLE
It is not work in Django 1.11.2

### ISSUE THREAD

**Issue by realsby** [jonasundderwolf/django-image-cropping#117]
I belive its javascript related. 
Crop area visible but not working.
Crop draggable corner boxes visible as line on the top only. 
After first click anywhere on pictures, corner boxes hidden forever. 
When clicked overflow element on images running but no selection.

Django (1.11.2)
django-suit (0.2.25)
django-image-cropping (1.0.4)
easy-thumbnails (2.4.1)
Pillow (4.1.1)

**Comment by realsby** [comment]
This solved my issue. Why you dont upgrade version :(
 https://github.com/jonasundderwolf/django-image-cropping/pull/114

**Comment by anrie** [comment]
This should be fixed in the latest release (1.1).
