### ISSUE TITLE
Add to installed apps.

### ISSUE THREAD

**Issue by PortEdison** [jonasundderwolf/django-image-cropping#118]
In readme. add 'image_cropping' to installed apps.

**Comment by anrie** [comment]
Really not sure what you are asking.

> By default django-image-cropping ships with an easy-thumbnails-backend which requires easy-thumbnails to **also be installed and added to the INSTALLED_APPS.**

**Comment by anrie** [comment]
Okay, maybe the also-clause was a bit too subtle ... the docs are now clearer: https://github.com/jonasundderwolf/django-image-cropping/commit/34cb1750fd1cd71c3591bdb52a566f4dcb4373b5
