### ISSUE TITLE
django-appconf downgrade

### ISSUE THREAD

**Issue by robmoggach** [jonasundderwolf/django-image-cropping#121]
does the `setup.py` absolutely require the specific version of django-appconf? (1.0.1)

**Comment by edwardoliveira** [comment]
We're facing message below in our app: 
`django-image-cropping 1.1.0 has requirement django-appconf==1.0.1, but you'll have django-appconf 1.0.2 which is incompatible.`

Would it be possible to upgrade it at least to 1.0.2?

Thanks!

**Comment by anrie** [comment]
We upgraded django-appconf to 1.0.2 in latest release (1.2)
