### ISSUE TITLE
Error for Admin ImageCroppingMixin in Django 2.1

### ISSUE THREAD

**Issue by Aupourbau** [jonasundderwolf/django-image-cropping#127]
Hello,

I m getting this error when applying the "ImageCroppingMixin" in Django 2.1 admin:
"render() got an unexpected keyword argument 'renderer'"

It might be because of Django 2.1 moving to Jquery 3.3.1.

**Comment by anrie** [comment]
An update for 2.0 / 2.1 is on its way. See #123 and #126.

**Comment by anrie** [comment]
Should be fixed in the latest 1.2 release.
