### ISSUE TITLE
no such table: example_image

### ISSUE THREAD

**Issue by NightHawk451** [jonasundderwolf/django-image-cropping#129]
I install the example and all of the requirements and when I run it and go to the base webpage (127.0.0.1:8000) I get this error messag: `no such table: example_image` Which comes from here:

`        image = Image.objects.all()[0]`

Not sure what is going on

**Comment by Zougi** [comment]
`python manage.py migrate` ?

**Comment by anrie** [comment]
The example app doesn't have migrations, so you need to call `manage.py migrate --run-syncdb` to create the necessary tables for the example app. (See: https://docs.djangoproject.com/en/2.1/ref/django-admin/#cmdoption-migrate-run-syncdb)
