### ISSUE TITLE
Selection area not shown in django admin 

### ISSUE THREAD

**Issue by logicappsource** [jonasundderwolf/django-image-cropping#132]
HI PLEASE help very frustating tried everything for hours now....
The selection area not showing up in admin... :/

Using Django :  2.1.3
I followed steps here are my code below. Thank you 
   
MY MODEL : 
from image_cropping import ImageRatioField, ImageCropField
 image                   = models.ImageField(upload_to="posts/", null=True, blank=True)
 image_cropped   = ImageRatioField('image', '305x236')
image_crop_field = ImageCropField(blank=True, null=True, upload_to="posts/")

MY MODEL ADMIN: 
from image_cropping import ImageCroppingMixin
class BlogAdmin(ImageCroppingMixin, admin.ModelAdmin):
admin.site.register(Post, BlogAdmin)

added to my installed apps:
 'easy_thumbnails',
 'image_cropping',

MY SETTINGS.py file 
from easy_thumbnails.conf import Settings as thumbnail_settings
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

THUMBNAIL_ALIASES = {
    '': {
        'avatar': {'size': (50, 50), 'crop': True},
    },
}

**Comment by logicappsource** [comment]
Any help or should i drop this framework

**Comment by logicappsource** [comment]
fuck this framework

**Comment by jonasvp** [comment]
Sorry to hear you feel this way! There seems to be a mismatch in expectations here: this is not a forum for free support. If you need our development services, feel free to contact our office at info@jonasundderwolf.de.

Otherwise, please use a forum such as www.stackoverflow.com to ask your question.
