### ISSUE TITLE
"Django Image Cropping" and "Django Autocomplete Light" are conflicting in the admin interface.

### ISSUE THREAD

**Issue by mogoh** [jonasundderwolf/django-image-cropping#140]
## Synopsis

If I use "Django Image Cropping" and "[Django Autocomplete Light](
https://github.com/yourlabs/django-autocomplete-light)" in the admin interface, image cropping is not working. This is probably due to some jquery issues.

## Before the upgrade

It worked in the past, when I used:

* django==1.11.26
* django-autocomplete-light==3.2.10
* django-image-cropping==1.1.0

## After the upgrade

I am not 100% sure, but I think it stopped working after the upgrade.

* django==2.2.8
* django-autocomplete-light==3.4.1
* django-image-cropping==1.2.0

## “Jcrop is not a function”

This is the error message:

![Bildschirmfoto vom 2019-12-13 12-19-01](https://user-images.githubusercontent.com/580975/70796591-f923c580-1da2-11ea-9014-16490d440b10.png)

So I guess it has to do something with Jcrop (a jquery plugin?) not getting loaded properly.

**Comment by bengosney** [comment]
This causes issues with sortable2 as well. PR#142 fixes that conflict and should solve your issue as well.

**Comment by MRigal** [comment]
@bengosney and @mogoh could you confirm that #148 also fixes the issue for you? If so I would merge this one rather than #142

**Comment by mogoh** [comment]
@MRigal  I am still having the same issue but I don't know if things are done right on my side.

Pipfile:
~~~
django-image-cropping  = {ref = "master",git = "https://github.com/anrie/django-image-cropping.git",editable = true}
~~~

![grafik](https://user-images.githubusercontent.com/580975/81570198-8d20aa00-93a0-11ea-976a-525361ff059c.png)

**Comment by anrie** [comment]
@mogoh The relevant changes are not on my **master** branch but on **cleanup_an_minify**: https://github.com/anrie/django-image-cropping/tree/cleanup_and_minify

Could you please try this branch and see if it changes the situation?

**Comment by mogoh** [comment]
@anrie Ah, right. Well I changed the branch but I still got the same error. :(

```
django-image-cropping  = {ref = "cleanup_and_minify", git = "https://github.com/anrie/django-image-cropping.git", editable = true}
```

**Comment by MRigal** [comment]
Hi @mogoh 
Thanks for keeping us informed! Any chance you could somehow give us failing code?
I see two options:
- Get the core (of all) of the your problematic setup to a repo we can access
- Create a PR modifying the `example` App so that it has the same failure
That would help us a lot to get to the point.

There is from what you show, at least no reason that it would fail with #148 and work with #142. Maybe 2 other widgets conflicting? Maybe some `def _media(self): js[]` overwriting not supported anymore by Django 2.2 ?

**Comment by mogoh** [comment]
I can't give you my source code, but I will create a reproduceable example. But I think it won't be done before monday.

**Comment by anrie** [comment]
@mogoh To me it looks like a misconfiguration. The file, that produces the error in the screenshot, should not be part of the installation anymore. See: https://github.com/anrie/django-image-cropping/tree/cleanup_and_minify/image_cropping/static/image_cropping/js/dist
There is no `image_cropping.js`, just a `image_cropping.min.js`

Can you please try uninstalling image cropping and reinstalling it again from the `cleanup_and_minify`-branch?

**Comment by mogoh** [comment]
@anrie Yes, you are right, but ... this is getting a bit longer.

I don't know how the misconfiguration came to be and I can't reproduce it.
Now I have changed thing but I still get an error.
I think this new error is related, but I can't reproduce it.

### The Error:

![Screenshot_20200526_175442](https://user-images.githubusercontent.com/580975/82922549-06f88c00-9f7a-11ea-8197-11eeee657cce.png)

### Some Attempts to reproduce:

Now I have tried to reproduce the error in a reduced envrionment but failed every time.
You can find all tries here:

* https://github.com/mogoh/django_examples/tree/master/ic_dal
* https://github.com/mogoh/django_examples/tree/master/cms_ic_dal

Now thows are working, so not much to see there.

### Some clue:

I still have a clue, why things are not working.
The order of javascript-files is still some mysterium to me.

#### Working:

In this working example `/static/image_cropping/js/dist/image_cropping.min.js` gets loaded after `/static/autocomplete_light/jquery.init.js`.

![Screenshot_20200526_180255](https://user-images.githubusercontent.com/580975/82923518-61deb300-9f7b-11ea-8874-2d94fca5443d.png)

#### Not Working:

In this now working example the order of `/static/autocomplete_light/jquery.init.js` and `/static/image_cropping/js/dist/image_cropping.min.js` is reverse.

![Screenshot_20200526_180812](https://user-images.githubusercontent.com/580975/82924302-6e174000-9f7c-11ea-97db-d0fe39880d79.png)

### Some thoughts

I think that autocomplete_light is overriding all jquery-plugins.
I tried changing the order of `INSTALLED_APPS` but that had no effect. :thinking: 
I don't know how to change the order of the javascript files and now I am out of Ideas.

**Comment by mogoh** [comment]
I could finally reproduce my error.
The problem is, that I have set

```
IMAGE_CROPPING_JQUERY_URL = 'admin/js/vendor/jquery/jquery.js'
```

You can find a complete example here: https://github.com/mogoh/django_examples/tree/master/ic_dal

I still don't know, why this causes an error, but it does.
Unsetting `IMAGE_CROPPING_JQUERY_URL` would be possible, but I prefere loading jquery only once.
Also I don't want to load jquery from some external source. :thinking:

**Comment by mogoh** [comment]
If I unset `IMAGE_CROPPING_JQUERY_URL`  everything works as expected. I still think further conflict should be fixed by other apps (Django Autocomplete Light).
As far as I am concerned this issue can be closed.
