### ISSUE TITLE
ImageCropWidget does not work outside of the admin

### ISSUE THREAD

**Issue by tiwei** [jonasundderwolf/django-image-cropping#17]
Hi guys, I couldn't find a ticket to this issue so I hope it's not a duplicate. Even if I explicitly assign the ImageCropWidget for my image form field, the image cropping widget isn't used outside of the admin. Instead a regular ClearableFileInput is rendered.

I'm using django crispy forms, but I also tried to render the field without the form-helper and had the same problem. It looks like that there is a problem with loading the jQuery/js.

There is a thread in the django user group, so I'm not the only one having the problem: https://groups.google.com/forum/#!topic/django-users/U6c-DysbGS4

Let me know if you need any additional information. Cheers!

**Comment by georgikoyrushki95** [comment]
Hi guys, I have the same problem. I have done all the initial set-up steps as was suggested by @jonasvp. Can you confirm that the application works with the latest django version? Thanks in advance for the help.

**Comment by jonathan-daniel** [comment]
Hello, im having the same problem event hough I have added the ratio field
