### ISSUE TITLE
Cropping Tool is only a text box

### ISSUE THREAD

**Issue by ipad12z** [jonasundderwolf/django-image-cropping#171]
These are all from the example. I just downloaded the files and install the requirements but I am not seeing the crop widget.

![image](https://user-images.githubusercontent.com/17017877/135425088-32b4bea6-701b-445e-aa70-f656c20f6879.png)

![image](https://user-images.githubusercontent.com/17017877/135425199-c66edf87-faca-4c8c-95b6-10421d16d30e.png)

![image](https://user-images.githubusercontent.com/17017877/135425274-ef5c30ac-7222-4815-a56d-c46bf13bf331.png)

I also made my own, following the guide:

![image](https://user-images.githubusercontent.com/17017877/135426220-05496c24-de19-4ef1-a053-2e8b81be82f1.png)

![image](https://user-images.githubusercontent.com/17017877/135426368-ae3db6c2-958b-4dcd-831b-82ebdb5c2f41.png)

But still has the same issue:

![image](https://user-images.githubusercontent.com/17017877/135426452-4bc749bb-d54f-49c4-baf0-086546b22b97.png)

**Comment by anrie** [comment]
@mschiegg is correct. We issued a new release where the default setting for `JQUERY_URL` is fixed.
@ipad12z Can you confirm that the widget works again in the latest version (`1.6.2`)?

**Comment by ipad12z** [comment]
@anrie  sorry for the late reply, I decided not to include the widget in my project anymore and stuck with the static cropping method. I will consider adding the widget to my project when I decided to add more features to my personal project. Thank you for your time!
