### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by jwedel** [jonasundderwolf/django-image-cropping#173]
Hi,

I've just upgraded to Django 4 and found at least one issue related to deprecated methods:
- in utils.py, there is an import of ugettext wich ihrs been removed and can be replaced by just gettext: 
```from django.utils.translation import gettext as _```

Maybe we can collect issues here. And then provide a PR.

**Comment by jwedel** [comment]
I tried but I can't event run the tests. Is there any contribution / building / testing documentation?

**Comment by anrie** [comment]
Hey @jwedel,
does this help and work for you? -> https://github.com/jonasundderwolf/django-image-cropping/blob/master/README.rst#testing

**Comment by jwedel** [comment]
@anrie

> Hey @jwedel,
> does this help and work for you? -> https://github.com/jonasundderwolf/django-image-cropping/blob/master/README.rst#testing

Yes, I searched for it but must have overlooked it. So I created a PR, see link above.
