### ISSUE TITLE
Cropping in inlines

### ISSUE THREAD

**Issue by dlancer** [jonasundderwolf/django-image-cropping#4]
It's possible add support for multiple cropping with inline related entries?
This would be awesome for posts or pages with several images.

**Comment by miodeqqq** [comment]
Hi there! I've got probably the same problem like @dlancer has.

I'm using ImageCroppingMixin in my admin.py:
<code>class RightListAdmin(ImageCroppingMixin, admin.StackedInline):</code>

And then I'm unable to modify images (cropping). Alll I see are only fields with image coordinates, like:
<code>Cropping: 265,0,1655,1030</code>
 When I disable it, works properly. Would tell me why it happens ? How to fix this ?
