### ISSUE TITLE
Cropping shown double on EditView and not at all on CreateView

### ISSUE THREAD

**Issue by philippeluickx** [jonasundderwolf/django-image-cropping#44]
Hey,

Just been struggling in getting this package implemented...
I managed to have crop through admin up and running, but having issues with implementing it in my ModelForm.

Currently it shows twice the cropping under each other on EditView and it only shows title and no cropping on CreateView... I do not have the impression I use anything funky, except crispy-forms. But even flukes when I do not apply crispy.

Running django 1.6.2 and django-image-cropping trunk.

Thanks for your help!

**Comment by kuanyui** [comment]
I also wonder if there any way to use image cropping in CreateView. Is there any progress?

**Comment by wanaryytel** [comment]
I too tried to implement it, needless to say without success. Waiting for some hints as well.

**Comment by anrie** [comment]
As discussed in another Issue (#61) it would be nice if we could leverage the FileReader-API for our cropping concerns. That would allow us to crop images without saving them first, which seems to be the problem with the CreateView.

As we use Image Cropping mainly in the backend this is not a top priority for us, but it would of course be great if someone would come up with Pull Request for this feature.
