### ISSUE TITLE
Remove JQuery/jcrop from Widget media

### ISSUE THREAD

**Issue by lpalomo** [jonasundderwolf/django-image-cropping#45]
I see that you are loading JQuery and JCrop with the form media. I wonder if this is the ideal thing to do because, I think, there is a huge possibility that JQuery (and possibly Jcrop) have already been loaded before on the template and therefore JQuery would be loaded multiples times. What do you think?, maybe saying in the docs that JQuery must be loaded before the widget would be enough (maybe saying what versions have been tested to work).

**Comment by anrie** [comment]
It's now possible to prevent the inclusion of the jQuery version bundled with `django-image-cropping`:

* https://github.com/jonasundderwolf/django-image-cropping/tree/5005764036fe680a98bf168a764108a67b3830bc#custom-jquery
* https://github.com/jonasundderwolf/django-image-cropping/blob/5005764036fe680a98bf168a764108a67b3830bc/image_cropping/widgets.py#L64
