### ISSUE TITLE
Requirement Django-appconf==0.6 not found

### ISSUE THREAD

**Issue by jungornti** [jonasundderwolf/django-image-cropping#64]
While installing:

    pip install django-appconf==0.6
    Downloading/unpacking django-appconf==0.6
      Could not find a version that satisfies the requirement django-appconf==0.6 (from versions: 1.0.1, 1.0.1)
    Cleaning up...
    No distributions matching the version for django-appconf==0.6
    Storing debug log for failure in ~/.pip/pip.log

**Comment by anrie** [comment]
Yeah, this should hopefully soon be resolved: https://twitter.com/jezdez/status/567314550555688960

**Comment by huogerac** [comment]
Hi @anrie, once the new django-appconf==1.0 seems to have just compatibility changes rather than structural ones. Is it possible to use the 1.0 version instead of the 0.6?

https://github.com/jezdez/django-appconf/blob/develop/docs/changelog.rst

**Comment by anrie** [comment]
I just published a new release that uses `django-appconf` 1.0.1:
https://pypi.python.org/pypi/django-image-cropping/0.9.2

**Comment by huogerac** [comment]
Thank you! you're rock!

**Comment by jungornti** [comment]
Thank you, thats good.
