### ISSUE TITLE
BUG: jQuery loss (can't use jQuery after import image_cropping.js)

### ISSUE THREAD

**Issue by FedeG** [jonasundderwolf/django-image-cropping#69]
Can't use jQuery after: "jQuery.noConflict(true)(function() {image_cropping.init();}); "
in: https://github.com/jonasundderwolf/django-image-cropping/blob/master/image_cropping/static/image_cropping/image_cropping.js

**Comment by FedeG** [comment]
Because "jQuery.noConflict(true)" overwrites $ and jQuery with previous version.

View details in: http://sundropsoftware.com/how-to-use-jquery-noconflict-the-right-way/

**Comment by anrie** [comment]
There is an older issue (#19) concerning the same subject.

All we do is to remove the jQuery that we included to make the widget work.
So you shouldn't rely on this jQuery version for anything you do in the admin.
Nevertheless `django.jQuery` and every jQuery you included separately should stay intact.

The only potential problem I can see is the recently added option to make Image Cropping NOT include its own jQuery version: https://github.com/jonasundderwolf/django-image-cropping#custom-jquery
Have you eventually set `IMAGE_CROPPING_JQUERY_URL` to `None`?

**Comment by FedeG** [comment]
Yes, I tried to configure the IMAGE_CROPPING_JQUERY_URL to None but neither worked.

Another thing I tried was to put a IMAGE_CROPPING_JQUERY_URL with a valid url jQuery and load jQuery after  but neither worked.

**Comment by anrie** [comment]
I can see the issue in the first case and we'll look into it.

Concerning the second case: As is said, this is the intended behaviour.
Either you include another jQuery yourself or you use Django's jQuery which is available as `django.jQuery`

**Comment by RaphaelKimmig** [comment]
I'm having the same issue. 
Using jquery.noconflict removes the existing jquery. When combined with `IMAGE_CROPPING_JQUERY_URL = None` this means no more jquery for me :-(

**Comment by anrie** [comment]
@RaphaelKimmig Yes, I can see the issue. 
There should be a check in `image_cropping.js` if `IMAGE_CROPPING_JQUERY_URL` was set to `None` and if this is the case, we shouldn't use `.noConflict()` so the JQuery provided by the user is left intact.

However I start thinking that the None-Option was maybe not best idea in the first place and we should simply restore the old behavior.

**Comment by anrie** [comment]
@RaphaelKimmig Can you check if this solves your problem: https://github.com/jonasundderwolf/django-image-cropping/tree/issue69/jquery_url?

**Comment by RaphaelKimmig** [comment]
@anrie Indeed it does. Thank you very much :-)

On another note - when installing django-image-cropping directly from git (via `setup.py install`) the static files are not included in the app folder. I noticed they are not listed in the manifest. Is that a bug or am I doing something wrong here?

**Comment by anrie** [comment]
Okay, there is a new release (1.0.2) that should solve this issue.

@RaphaelKimmig The static files should now be included if you install directly from Github.

**Comment by RaphaelKimmig** [comment]
@anrie Awesome, thank you!
