### ISSUE TITLE
Clean cached images

### ISSUE THREAD

**Issue by nguyentranvu** [jonasundderwolf/django-image-cropping#70]
I see that there is many cached images when we're cropping the photo. I have a couple of questions:
1. How can we clean it? 
2. How can we delete the old photo in the image field when we change it to a new file? I guess It should be there

Thank you

**Comment by anrie** [comment]
Hm, as we are using `easy_thumbnails` for thumbnail generation you should probably take a look at the [options]( https://github.com/SmileyChris/easy-thumbnails/blob/master/easy_thumbnails/management/commands/thumbnail_cleanup.py#L13) it provides.

Concerning the old photo: This is pretty much Django's default behavior. But there a solutions if you need to address this: http://stackoverflow.com/questions/2878490/how-to-delete-old-image-when-update-imagefield
