### ISSUE TITLE
Exception when cropping a image

### ISSUE THREAD

**Issue by henriquechehad** [jonasundderwolf/django-image-cropping#73]
Hello,

There is a image that returns a exception when is called the "cropped_thumbnail" templatetag.

IOError
image file is truncated (0 bytes not processed)

![crop-error](https://cloud.githubusercontent.com/assets/1929407/8875553/7917aff2-31f0-11e5-8a5e-75b61fb7e7bf.png)

**Comment by anrie** [comment]
This should be fixed in the latest release.
