### ISSUE TITLE
Doesn't work with s3 bucket

### ISSUE THREAD

**Issue by krisfields** [jonasundderwolf/django-image-cropping#76]
I've got everything working perfectly locally, but it breaks in our staging environment, where the get_thumbnailer method returns a url to an image that never made it to our s3 bucket.  For example, profile_image.jpg will be in our bucket but not profile_image.jpg.430x360_q85_box-177%2C0%2C383%2C206_crop_detail.jpg, which is the get_thumbnailer generated url.  

I'm trying to dig into the code now to see what's going on but thought I'd post it here in case you have any ideas.

**Comment by pakzech** [comment]
Same here. It seems an issue with easy_thumbnails.

**Comment by pakzech** [comment]
Found the solution. This will do the trick:

```python
THUMBNAIL_DEFAULT_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
THUMBNAIL_BASEDIR = 'thumbs/' # Optional but recommended
```

**Comment by espenhogbakk** [comment]
To anyone looking, this did in did work.

**Comment by jonasvp** [comment]
Great, thanks for helping out @pakzech!
