### ISSUE TITLE
Django cropping on AWS, django 1.8.8

### ISSUE THREAD

**Issue by ppeczek** [jonasundderwolf/django-image-cropping#88]
Hi,

Unfortunately there is no clear documentation for using library with AWS. It seems that AWS is not generating files on the server. From templatetag thumbnail I get probably proper src of image: "events_big/12687976_10208692743942939_7164020722604166972_n.jpg.1250x510_q85_box-0%2C66%2C850%2C412_crop_detail.jpg", but given image does not exist: "Failed to load given URL".

I use django-image-cropping 1.0.3. I used django-image-cropping-amazon-s3 but the result was the same. Is it fault in code or in AWS config?

**Comment by marthall** [comment]
+1

**Comment by ppeczek** [comment]
Not yet, just skipped to another functionality. Set image as background in css and manipulate it with width, height, top and left properties.

**Comment by marthall** [comment]
Ok, seems like this is related: https://github.com/SmileyChris/easy-thumbnails/issues/284

I will test it tomorrow and report back/fix documentation.

**Comment by jmrivas86** [comment]
@ppeczek @marthall the solution is to set THUMBNAIL_DEFAULT_STORAGE for AWS:

THUMBNAIL_DEFAULT_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

**Comment by anrie** [comment]
Ah, thanks for the solution @jmrivas86
