### ISSUE TITLE
Using Image Cropping With User (not just in Admin) does not work.

### ISSUE THREAD

**Issue by gabe-dol** [jonasundderwolf/django-image-cropping#90]
I do everything as the doc says. Then I do {{ form.media }} in the head and {{ form }} in the body. The file upload works just fine, but the user cannot see the image in order to crop it! How do i fix this?

**Comment by lomholdt** [comment]
Are you including the 'cropping' area in your form? The plugin does not change the upload field (as i thought to begin with), you have to add the cropping field to your template.

**Comment by bernardojedi** [comment]
I am having the same issue here, I noticed that my {{ form.media }} is not rendering to anything. I have tried using the ImageCropWidget on both ImageCropField and ImageRatioField. @lomholdt Can you elaborate your solution?

**Comment by lomholdt** [comment]
I only include {% load cropping %} because I am only using the {% cropped thumbnail ... %} tag.
In my form I have

```
class MyEditForm(forms.ModelForm):

    class Meta:

        model = ModelName
        fields = ['name',
                  'email',
                  ...
                  'logo',
                  'cropping_logo',
                  ]

        widgets = {
            'logo': ImageCropWidget,
        }
```

**Comment by gabe-dol** [comment]
@lomholdt Yeah IDK what exactly is causing my issue. I'm on on python 3.4, django 1.8. Currently I am  just using a profile pic that doesnt crop, but re-sizes the uploaded image, and it seems to work fine. thanks
