### ISSUE TITLE
Convert output images to a specific format

### ISSUE THREAD

**Issue by ojwoodford** [jonasundderwolf/django-image-cropping#94]
Can this toolbox have the option to convert the cropped images to a particular file format? For example, if the original image is a .png, can we ensure the the cropped image has format .jpg?

**Comment by anrie** [comment]
You should check `easy_thumbnails` settings concerning output formats and file extensions.

This will probably do the trick: http://easy-thumbnails.readthedocs.io/en/2.1/ref/settings/#easy_thumbnails.conf.Settings.THUMBNAIL_PRESERVE_EXTENSIONS
