### ISSUE TITLE
Max height and width for large images not working

### ISSUE THREAD

**Issue by userdefinable** [jonasundderwolf/django-image-cropping#95]
Setting maximum height and width of large images is not working. I believe this is owing to undefined boxHeight and boxWidth due to incorrect variable names.

django-image-cropping/image_cropping/static/image_cropping/image_cropping.js

lines 57 to 61

$this.data('box_max_width') should be $this.data('box-max-width') in two occurrences

$this.data('box_max_height') should be $this.data('box-max-height') in two occurrences

**Comment by anrie** [comment]
@userdefinable 

Could you provide a PR  (ideally with a test) for the issue?

**Comment by MRigal** [comment]
Hi @userdefinable 
Time has passed, but could you eventually confirm that the PR #131 has fixed your issue?

**Comment by MRigal** [comment]
Time to close this. Please re-open if it wasn't fixed @userdefinable
